### ISSUE TITLE
Algunos pdf vienen vacios en los mails de trabajos aceptados

### ISSUE THREAD

**Issue by hella815** [Zabalero/Trabajos_Programados#4]
Nos reportan que para gran parte de las tareas los pdf adjuntos vienen vacios.

Esto pasa tanto para los mails de Tareas aceptadas como en las propias tareas que aparecen en la web.

![imagen](https://user-images.githubusercontent.com/39184112/54033177-e1843480-41b3-11e9-946e-50a1eeaac57d.png)

**Comment by Zabalero** [comment]
-	Habían problemas en el manejo de los output buffers
-	Problemas en la codificación
-	Problemas en las librerías de clases que generan los pdf
-	Problemas en el manejo de las cadenas que se envían a la cola de impresión PDF
-	Problemas en el manejo del cache
